### ISSUE TITLE
Holding the right click on a player kicks him from the server

### ISSUE THREAD

**Issue by Kxsumi** [Calvineries/physicsgun#1] opened 2023-04-16 14:07 UTC
According to them they are kicked for "Exceeding Packet Rate Limit"

**Comment by Calvineries** [comment] 2023-04-16 14:22
https://youtu.be/QFMpU5u8O7k
I can't reproduce this issue.
I made this video on a localhost server, but my plugin is also installed on my mini games server, and I don't encounter this issue.

Check that you are using the latest version of the plugin.
Try again by setting allow-flight to true in server.properties

**Comment by Kxsumi** [comment] 2023-04-16 14:28
> https://youtu.be/QFMpU5u8O7k I can't reproduce this issue. I made this video o a paper-spigot 1.19.4 localhost server, but my plugin is also installed on my mini games server, and I don't encounter this issue.
> 
> Check that you are using the latest version of the plugin. Try again by setting allow-flight to true in server.properties Do you use paper, spigot or something else? and on which version of minecraft?

We use Purpur 1.19.3. I have found it ONLY happens when you hold right click (not tap) while hovering over someone.

**Comment by Kxsumi** [comment] 2023-04-16 14:32
Allow flight is also already enabled.

**Comment by Calvineries** [comment] 2023-04-16 14:33
Ok, I managed to reproduce it.
Until I fix the issue, you only have to do 1 right click on the player as indicated on the spigot page.

**Comment by Calvineries** [comment] 2023-04-17 07:10
Fixed in 1.4.
Download: https://cdn.discordapp.com/attachments/706932420615864332/1097418462231547944/Physicsgun.jar

**Closed** 2023-04-17 07:10 UTC
